version: '3'
services:
    redis:
        container_name: fht-cache
        image: redis
        ports:
            - "6379:6379"
    mongo:
        container_name: fht-db
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - ./localFolder:/data/db
    api:
        container_name: fht-api
        depends_on:
            - redis
            - mongo
        build: .
        ports:
            - "3000:3000"
