version: '3'
services:
  api:
    image: fantasy-hockey-tool-express
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
  web-cli:
    image: fantasy-hockey-tool-express
    networks:
      - backend
    command: sh
networks:
  backend:
    driver: bridge
